# Generated by Django 4.2.7 on 2026-05-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_participant_is_muted_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='chat_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('admitted', 'Admitted'), ('declined', 'Declined')], default='waiting', max_length=20),
        ),
    ]
