# Generated by Django 4.2.7 on 2026-05-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_chat_enabled_participant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='invite_link',
        ),
        migrations.AddField(
            model_name='meeting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('instant', 'Instant'), ('scheduled', 'Scheduled')], db_index=True, default='instant', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('ended', 'Ended')], db_index=True, default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='left_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('admitted', 'Admitted'), ('declined', 'Declined')], db_index=True, default='waiting', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('meeting', 'display_name'), name='unique_active_participant'),
        ),
    ]
